export const githubEventMultipleCommits = {
  "ref": "refs/heads/main",
  "before": "42a2ea4757cc02e7d7b667060d2a51cee1f3ca36",
  "after": "55343a48d82719e832424b9ea5bae2bc634b19aa",
  "repository": {
      "id": 597809846,
      "node_id": "R_kgDOI6Hatg",
      "name": "demo-monorepo-deployer",
      "full_name": "frankliu81/demo-monorepo-deployer",
      "private": false,
      "owner": {
          "name": "frankliu81",
          "email": "frank_liu@acl.com",
          "login": "frankliu81",
          "id": 16039389,
          "node_id": "MDQ6VXNlcjE2MDM5Mzg5",
          "avatar_url": "https://avatars.githubusercontent.com/u/16039389?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/frankliu81",
          "html_url": "https://github.com/frankliu81",
          "followers_url": "https://api.github.com/users/frankliu81/followers",
          "following_url": "https://api.github.com/users/frankliu81/following{/other_user}",
          "gists_url": "https://api.github.com/users/frankliu81/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/frankliu81/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/frankliu81/subscriptions",
          "organizations_url": "https://api.github.com/users/frankliu81/orgs",
          "repos_url": "https://api.github.com/users/frankliu81/repos",
          "events_url": "https://api.github.com/users/frankliu81/events{/privacy}",
          "received_events_url": "https://api.github.com/users/frankliu81/received_events",
          "type": "User",
          "site_admin": false
      },
      "html_url": "https://github.com/frankliu81/demo-monorepo-deployer",
      "description": null,
      "fork": false,
      "url": "https://github.com/frankliu81/demo-monorepo-deployer",
      "forks_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/forks",
      "keys_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/teams",
      "hooks_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/hooks",
      "issue_events_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/issues/events{/number}",
      "events_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/events",
      "assignees_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/assignees{/user}",
      "branches_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/branches{/branch}",
      "tags_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/tags",
      "blobs_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/languages",
      "stargazers_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/stargazers",
      "contributors_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/contributors",
      "subscribers_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/subscribers",
      "subscription_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/subscription",
      "commits_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/contents/{+path}",
      "compare_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/merges",
      "archive_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/downloads",
      "issues_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/issues{/number}",
      "pulls_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/labels{/name}",
      "releases_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/releases{/id}",
      "deployments_url": "https://api.github.com/repos/frankliu81/demo-monorepo-deployer/deployments",
      "created_at": 1675619525,
      "updated_at": "2023-02-05T18:41:35Z",
      "pushed_at": 1680891138,
      "git_url": "git://github.com/frankliu81/demo-monorepo-deployer.git",
      "ssh_url": "git@github.com:frankliu81/demo-monorepo-deployer.git",
      "clone_url": "https://github.com/frankliu81/demo-monorepo-deployer.git",
      "svn_url": "https://github.com/frankliu81/demo-monorepo-deployer",
      "homepage": null,
      "size": 327,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "main",
      "stargazers": 0,
      "master_branch": "main"
  },
  "pusher": {
      "name": "frankliu81",
      "email": "frank_liu@acl.com"
  },
  "sender": {
      "login": "frankliu81",
      "id": 16039389,
      "node_id": "MDQ6VXNlcjE2MDM5Mzg5",
      "avatar_url": "https://avatars.githubusercontent.com/u/16039389?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/frankliu81",
      "html_url": "https://github.com/frankliu81",
      "followers_url": "https://api.github.com/users/frankliu81/followers",
      "following_url": "https://api.github.com/users/frankliu81/following{/other_user}",
      "gists_url": "https://api.github.com/users/frankliu81/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/frankliu81/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/frankliu81/subscriptions",
      "organizations_url": "https://api.github.com/users/frankliu81/orgs",
      "repos_url": "https://api.github.com/users/frankliu81/repos",
      "events_url": "https://api.github.com/users/frankliu81/events{/privacy}",
      "received_events_url": "https://api.github.com/users/frankliu81/received_events",
      "type": "User",
      "site_admin": false
  },
  "created": false,
  "deleted": false,
  "forced": true,
  "base_ref": null,
  "compare": "https://github.com/frankliu81/demo-monorepo-deployer/compare/42a2ea4757cc...55343a48d827",
  "commits": [
      {
          "id": "a90b210352933827f2f01746774a1977740103a2",
          "tree_id": "0dfe0ea3c3016cefa62585e00efaba9a7a90da87",
          "distinct": true,
          "message": "generate test event without service1",
          "timestamp": "2023-04-07T11:09:32-07:00",
          "url": "https://github.com/frankliu81/demo-monorepo-deployer/commit/a90b210352933827f2f01746774a1977740103a2",
          "author": {
              "name": "Frank Liu",
              "email": "frankliu81@gmail.com",
              "username": "frankliu81"
          },
          "committer": {
              "name": "Frank Liu",
              "email": "frankliu81@gmail.com",
              "username": "frankliu81"
          },
          "added": [
              "services/monorepo-deployer/test/lambda-event-example.ts",
              "services/service2/test/hello.test.ts"
          ],
          "removed": [
              "services/service2/test/service2.test.ts"
          ],
          "modified": [
              "services/monorepo-deployer/src/config-evaluator.ts",
              "services/monorepo-deployer/src/monorepo-deployer.lambda.ts",
              "services/monorepo-deployer/test/github-event-no-service1.ts",
              "services/service2/src/index.ts"
          ]
      },
      {
          "id": "55343a48d82719e832424b9ea5bae2bc634b19aa",
          "tree_id": "0b2060f158e8da2d8336d25ed016df179b948166",
          "distinct": true,
          "message": "additional commit",
          "timestamp": "2023-04-07T11:09:56-07:00",
          "url": "https://github.com/frankliu81/demo-monorepo-deployer/commit/55343a48d82719e832424b9ea5bae2bc634b19aa",
          "author": {
              "name": "Frank Liu",
              "email": "frankliu81@gmail.com",
              "username": "frankliu81"
          },
          "committer": {
              "name": "Frank Liu",
              "email": "frankliu81@gmail.com",
              "username": "frankliu81"
          },
          "added": [],
          "removed": [],
          "modified": [
              "services/service2/bin/service2.ts"
          ]
      }
  ],
  "head_commit": {
      "id": "55343a48d82719e832424b9ea5bae2bc634b19aa",
      "tree_id": "0b2060f158e8da2d8336d25ed016df179b948166",
      "distinct": true,
      "message": "additional commit",
      "timestamp": "2023-04-07T11:09:56-07:00",
      "url": "https://github.com/frankliu81/demo-monorepo-deployer/commit/55343a48d82719e832424b9ea5bae2bc634b19aa",
      "author": {
          "name": "Frank Liu",
          "email": "frankliu81@gmail.com",
          "username": "frankliu81"
      },
      "committer": {
          "name": "Frank Liu",
          "email": "frankliu81@gmail.com",
          "username": "frankliu81"
      },
      "added": [],
      "removed": [],
      "modified": [
          "services/service2/bin/service2.ts"
      ]
  }
}